import streamlit as st


def render_diet_plan(diet_plan: str):
    """Render the diet plan in the Diet Plan tab."""
    st.markdown("### Your Personalized 7-Day Diet Plan")
    st.caption("Generated by your AI Dietitian — adjust portions to your comfort level.")
    st.divider()
    st.markdown(diet_plan)
