import streamlit as st


def render_fitness_plan(fitness_plan: str):
    """Render the fitness plan in the Fitness Plan tab."""
    st.markdown("### Your Personalized Weekly Fitness Plan")
    st.caption("Generated by your AI Personal Trainer — listen to your body and rest when needed.")
    st.divider()
    st.markdown(fitness_plan)
